# Exercise 1 - 向量 和, 内积, 外积

In [9]:
import numpy as np

# 定义向量X和Y
X = np.array([1, 2, 3])
Y = np.array([3, 2, 1])

# 计算向量和
vector_sum = X + Y

# 计算内积
inner_product = np.dot(X, Y)

# 计算外积
outer_product = np.outer(Y, X)

vector_sum, inner_product, outer_product


(array([4, 4, 4]),
 10,
 array([[3, 6, 9],
        [2, 4, 6],
        [1, 2, 3]]))

# Exercise 2 - 矩阵 和, 积
- 和: 可交换
- 积: 不可狡猾, 除非 对称矩阵

In [10]:
import numpy as np

# 定义矩阵A和B
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[0, 1, 0],
              [1, 2, 3],
              [-1, 0, 1]])

# 计算矩阵和 A + B 和 B + A
matrix_sum_A_B = A + B
matrix_sum_B_A = B + A

# 计算矩阵乘积 A * B 和 B * A
matrix_product_A_B = np.dot(A, B)
matrix_product_B_A = np.dot(B, A)

# 打印结果
print("A + B:")
print(matrix_sum_A_B)
print("B + A:")
print(matrix_sum_B_A)
print("A * B:")
print(matrix_product_A_B)
print("B * A:")
print(matrix_product_B_A)


A + B:
[[ 1  3  3]
 [ 5  7  9]
 [ 6  8 10]]
B + A:
[[ 1  3  3]
 [ 5  7  9]
 [ 6  8 10]]
A * B:
[[-1  5  9]
 [-1 14 21]
 [-1 23 33]]
B * A:
[[ 4  5  6]
 [30 36 42]
 [ 6  6  6]]


# Exercise 3 - 逆矩阵

In [11]:
# 定义矩阵A
A = np.array([[1, 2], [-2, 1]])

# 计算矩阵A的逆
A_inverse = np.linalg.inv(A)
print(A_inverse)

# 验证矩阵A及其逆的乘积是否为2x2单位矩阵
identity_matrix = np.dot(A, A_inverse)
print(identity_matrix)

[[ 0.2 -0.4]
 [ 0.4  0.2]]
[[1. 0.]
 [0. 1.]]


# Exercise 4 - 线性独立 (秩)

## 秩
在矩阵中，秩是指矩阵中行向量或列向量组成的最大线性无关组的大小。

如果一个矩阵的秩等于其列数，这意味着矩阵中的每一列都是线性无关的，没有一列可以通过其他列的线性组合来表示。这样的矩阵被称为满秩矩阵。
如果一个矩阵的秩小于其列数，这意味着矩阵中的某些列是线性相关的。换句话说，至少有一列可以用其他列的线性组合来表示。

秩也可以用来描述行向量的线性无关性。

## 线性无关。
如果一组向量是线性无关的，那意味着没有任何一个向量可以通过其他向量的线性组合来表示。例如，向量 (1,0) 和 (0,1) 在二维空间中是线性无关的，因为你无法使用其中一个向量乘以某个数来得到另一个向量。如果一组向量中至少有一个向量可以通过其他向量的线性组合来表示，那么这组向量就是线性相关的。

举个例子，考虑以下两个矩阵：

矩阵1:
[ 10
  01 ]
矩阵2:
[ 11​ 
  22 ]
矩阵1的秩是2，因为两行两列都是线性无关的。矩阵2的秩是1，因为第二列只是第一列的两倍，所以它们是线性相关的。

In [12]:
import numpy as np

# 定义向量A, B, C
A = np.array([1, 2, -3, 4])
B = np.array([1, 1, 0, 2])
C = np.array([-1, -2, 1, 1])

# 创建矩阵，将向量A, B, C作为列向量
matrix = np.column_stack((A, B, C))

# 计算矩阵的秩
rank = np.linalg.matrix_rank(matrix)

rank


3

In [13]:
from sympy import symbols, Eq, solve

# 定义λ1, λ2, λ3为符号变量
λ1, λ2, λ3 = symbols('λ1 λ2 λ3')

# 建立方程组
eq1 = Eq(λ1 + λ2 - λ3, 0)
eq2 = Eq(2*λ1 + λ2 - 2*λ3, 0)
eq3 = Eq(-3*λ1 + λ3, 0)
eq4 = Eq(4*λ1 + 2*λ2 + λ3, 0)

# 解方程组
solution = solve((eq1, eq2, eq3, eq4), (λ1, λ2, λ3))

solution


{λ1: 0, λ2: 0, λ3: 0}

# Exercise 5 - 秩

In [16]:
# 定义矩阵A和B
A = np.array([[1, 0, 1],
              [0, 1, 1],
              [0, 0, 0]])

B = np.array([[1, 2, 1],
              [-2, -3, 1],
              [3, 5, 0]])

# 计算矩阵A和B的秩
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

rank_A, rank_B


(2, 2)

# Exercise 6 - 特征值, 特征向量

In [20]:
from sympy import Matrix

# Define matrix A
A = Matrix([[4, 2], 
            [1, 3]])

# Calculate eigenvalues
eigenvals = A.eigenvals()

# Calculate eigenvectors
eigenvects = A.eigenvects()

print("Eigenvalues:", eigenvals)
print("Eigenvectors:", eigenvects)



Eigenvalues: {5: 1, 2: 1}
Eigenvectors: [(2, 1, [Matrix([
[-1],
[ 1]])]), (5, 1, [Matrix([
[2],
[1]])])]
